import { test, expect } from '@playwright/test';
import { PageFactory } from './pages/PageFactory';

/**
 * Budget Management — happy path & negative tests
 *
 * User story: "As a user I can view my budget per category, edit budget limits,
 * and see a running total/remaining indicator so that I can control my spending."
 *
 * Generated by the Amikoo Jira-to-tests worker (2026-09-09).
 */

test.describe('Budget Management — happy path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await page.getByRole('button', { name: /budgets/i }).click();
    await expect(page.getByRole('heading', { name: 'Budgets' })).toBeVisible();
  });

  test('Budgets section renders Total Budget, Total Spent, and Remaining KPI cards', async ({ page }) => {
    await expect(page.getByText('Total Budget')).toBeVisible();
    await expect(page.getByText('Total Spent')).toBeVisible();
    await expect(page.getByText('Remaining')).toBeVisible();
  });

  test('all 8 spending categories are displayed as budget cards', async ({ page }) => {
    const categories = ['Housing', 'Food', 'Transport', 'Entertainment', 'Health', 'Utilities', 'Shopping', 'Subscriptions'];
    for (const cat of categories) {
      await expect(page.getByText(cat).first()).toBeVisible();
    }
  });

  test('each category card shows a progress bar and a budget input', async ({ page }) => {
    // Housing always has exactly 1 seeded transaction — pick it as a stable target
    const housingCard = page.locator('div').filter({ hasText: /^🏠/ }).first();
    await expect(housingCard).toBeVisible();

    // Budget spinbutton (number input) should be present
    const budgetInput = housingCard.getByRole('spinbutton');
    await expect(budgetInput).toBeVisible();
  });

  test('editing a budget limit immediately updates the remaining indicator', async ({ page }) => {
    // Locate Housing category card and its budget input
    const housingCard = page.locator('div', { hasText: /^Housing/ }).first();
    const budgetInput = housingCard.getByRole('spinbutton');

    // Set a high budget (well above any seeded spend) — remaining should be positive
    await budgetInput.fill('9999');
    await budgetInput.dispatchEvent('change');

    // "left" label appears when remaining > 0
    await expect(housingCard.getByText(/left/)).toBeVisible();
  });

  test('switching months recalculates the Total Spent KPI', async ({ page }) => {
    const getSpent = async () =>
      page
        .getByText('Total Spent')
        .locator('..')
        .getByText(/\$[\d,]+/)
        .first()
        .textContent();

    await page.getByRole('button', { name: 'Feb' }).click();
    const febSpent = await getSpent();

    await page.getByRole('button', { name: 'Mar' }).click();
    const marSpent = await getSpent();

    // Both values must be valid dollar amounts
    expect(febSpent).toMatch(/\$[\d,]+/);
    expect(marSpent).toMatch(/\$[\d,]+/);
  });

  test('Remaining KPI equals Total Budget minus Total Spent', async ({ page }) => {
    const parseAmt = (t: string | null) => parseFloat((t ?? '0').replace(/[$,]/g, ''));

    const budget = parseAmt(
      await page.getByText('Total Budget').locator('..').getByText(/\$[\d,]+/).first().textContent()
    );
    const spent = parseAmt(
      await page.getByText('Total Spent').locator('..').getByText(/\$[\d,]+/).first().textContent()
    );
    const remaining = parseAmt(
      await page.getByText('Remaining').locator('..').getByText(/\$[\d,]+/).first().textContent()
    );

    // Allow $1 rounding tolerance
    expect(Math.abs(remaining - (budget - spent))).toBeLessThanOrEqual(1);
  });

  test('category search filters the displayed budget cards', async ({ page }) => {
    // Type "hous" — only the Housing card should be visible
    await page.getByPlaceholder('Search categories…').fill('hous');

    await expect(page.getByText('Housing').first()).toBeVisible();
    await expect(page.getByText('Food').first()).not.toBeVisible();
  });
});

test.describe('Budget Management — negative path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await page.getByRole('button', { name: /budgets/i }).click();
    await expect(page.getByRole('heading', { name: 'Budgets' })).toBeVisible();
  });

  test('setting a budget limit to zero makes the category 100% over budget', async ({ page }) => {
    // Find the Food card (has multiple seeded transactions so spent > 0)
    const foodCard = page.locator('div', { hasText: /^Food/ }).first();
    const budgetInput = foodCard.getByRole('spinbutton');

    // Set budget to 0 — any spend makes it 100%+ over
    await budgetInput.fill('0');
    await budgetInput.dispatchEvent('change');

    // Progress bar should show the red over-budget state via "over" text
    await expect(foodCard.getByText(/over/)).toBeVisible();
  });

  test('category search with no matching text hides all budget cards', async ({ page }) => {
    await page.getByPlaceholder('Search categories…').fill('zzz_no_match');

    // None of the 8 categories should be visible
    const categories = ['Housing', 'Food', 'Transport', 'Entertainment', 'Health', 'Utilities', 'Shopping', 'Subscriptions'];
    for (const cat of categories) {
      await expect(page.getByText(cat)).toHaveCount(0);
    }
  });

  test('Remaining KPI turns negative when Total Spent exceeds Total Budget', async ({ page }) => {
    // Set ALL categories to budget 0 — total budget drops to 0, remaining goes negative
    const inputs = page.getByRole('spinbutton');
    const count = await inputs.count();
    for (let i = 0; i < count; i++) {
      await inputs.nth(i).fill('0');
      await inputs.nth(i).dispatchEvent('change');
    }

    const remainingCard = page.getByText('Remaining').locator('..');
    // The remaining value should be negative (contains a minus or the KPI card colour changes)
    const remainingText = await remainingCard.getByText(/\$[\d,]+/).first().textContent();
    const value = parseFloat((remainingText ?? '0').replace(/[$,]/g, ''));
    // With 0 budget and non-zero spend, remaining must be <= 0
    expect(value).toBeLessThanOrEqual(0);
  });

  test('clearing the category search restores all 8 category cards', async ({ page }) => {
    const searchInput = page.getByPlaceholder('Search categories…');

    await searchInput.fill('Food');
    await expect(page.getByText('Housing')).toHaveCount(0);

    await searchInput.fill('');
    // All 8 must return
    const categories = ['Housing', 'Food', 'Transport', 'Entertainment', 'Health', 'Utilities', 'Shopping', 'Subscriptions'];
    for (const cat of categories) {
      await expect(page.getByText(cat).first()).toBeVisible();
    }
  });
});
