import { test, expect } from '@playwright/test';
import { PageFactory } from './pages/PageFactory';

/**
 * Budget Management — user story tests
 *
 * User story (WP-020):
 *   As a logged-in user I want to view my monthly budget usage by category,
 *   edit budget limits inline, and search/filter categories so that I can
 *   stay within my spending targets.
 *
 * Acceptance criteria:
 *   - 3 KPI cards (Total Budget, Total Spent, Remaining) are visible.
 *   - All 8 spending category cards are displayed by default.
 *   - Editing a category's budget limit updates the stored value.
 *   - Category search input filters the visible category cards.
 *   - Clearing the search restores all 8 cards.
 *   - Switching months updates the Total Spent KPI.
 *   - Remaining = Total Budget − Total Spent (within ±$1 rounding tolerance).
 *
 * Generated by Amikoo Worker: Jira-user-story-tests-automated — 2026-09-16
 */

// ─── Happy Path ──────────────────────────────────────────────────────────────

test.describe('Budget Management — happy path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    // Navigate to Budgets tab
    await factory.budgets().navigate();
  });

  test('three KPI cards are visible after navigating to Budgets', async ({ page }) => {
    await expect(page.getByText('Total Budget')).toBeVisible();
    await expect(page.getByText('Total Spent')).toBeVisible();
    await expect(page.getByText('Remaining')).toBeVisible();
  });

  test('all 8 category budget spinbuttons are present by default', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();
    // Each category has a numeric input; there are 8 seeded categories
    await expect(budgets.categoryCards).toHaveCount(8);
  });

  test('category search for "Housing" shows exactly one card', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();

    await budgets.searchCategory('Housing');

    // Only the Housing input should remain visible
    await expect(budgets.categoryCards).toHaveCount(1);
  });

  test('clearing the category search input restores all 8 cards', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();

    await budgets.searchCategory('Food');
    await expect(budgets.categoryCards).toHaveCount(1);

    await budgets.clearSearch();
    await expect(budgets.categoryCards).toHaveCount(8);
  });

  test('switching from March to January changes the Total Spent KPI', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();

    // March is the default; read its value
    await budgets.selectMonth('Mar');
    const marchSpent = await page
      .locator('.rounded-2xl')
      .filter({ hasText: 'Total Spent' })
      .first()
      .locator('p.text-xl, p.text-2xl')
      .first()
      .innerText();

    // Switch to January
    await budgets.selectMonth('Jan');
    const janSpent = await page
      .locator('.rounded-2xl')
      .filter({ hasText: 'Total Spent' })
      .first()
      .locator('p.text-xl, p.text-2xl')
      .first()
      .innerText();

    // Different months produce different spending totals in seeded data
    expect(janSpent).not.toBe(marchSpent);
  });

  test('category search is case-insensitive — "food" matches Food card', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();

    await budgets.searchCategory('food');
    await expect(budgets.categoryCards).toHaveCount(1);
  });

  test('Budgets tab is reachable via the sidebar after login', async ({ page }) => {
    // Already navigated in beforeEach — just confirm the KPI is visible
    await expect(page.getByText('Total Budget')).toBeVisible();
  });
});

// ─── Negative / Edge Cases ────────────────────────────────────────────────────

test.describe('Budget Management — negative & edge cases', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.budgets().navigate();
  });

  test('searching for a non-existent category name hides all category cards', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();

    await budgets.searchCategory('xxxxxxxxnotacategory');

    // No inputs should be visible
    await expect(budgets.categoryCards).toHaveCount(0);
  });

  test('category search with partial match "Trans" shows only Transport card', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();

    await budgets.searchCategory('Trans');

    await expect(budgets.categoryCards).toHaveCount(1);
  });

  test('Remaining KPI is always less than or equal to Total Budget', async ({ page }) => {
    // Remaining = Total Budget − Total Spent; it cannot exceed Total Budget
    const totalBudgetRaw = await page
      .locator('.rounded-2xl')
      .filter({ hasText: 'Total Budget' })
      .first()
      .locator('p.text-xl, p.text-2xl')
      .first()
      .innerText();

    const remainingRaw = await page
      .locator('.rounded-2xl')
      .filter({ hasText: 'Remaining' })
      .first()
      .locator('p.text-xl, p.text-2xl')
      .first()
      .innerText();

    const totalBudget = parseFloat(totalBudgetRaw.replace(/[$,]/g, ''));
    const remaining = parseFloat(remainingRaw.replace(/[$,]/g, ''));

    // Remaining may be negative (over-budget) but must not exceed total budget
    expect(remaining).toBeLessThanOrEqual(totalBudget + 1); // +1 for rounding
  });

  test('rapid month switching does not crash the app — KPI cards stay visible', async ({ page }) => {
    const budgets = new PageFactory(page).budgets();

    // Click through all months quickly
    await budgets.selectMonth('Jan');
    await budgets.selectMonth('Mar');
    await budgets.selectMonth('Feb');
    await budgets.selectMonth('Mar');

    // App must remain stable; KPI cards must still be visible
    await expect(page.getByText('Total Budget')).toBeVisible();
    await expect(page.getByText('Total Spent')).toBeVisible();
    await expect(page.getByText('Remaining')).toBeVisible();
  });
});
