import { test, expect } from '@playwright/test';
import { PageFactory } from './pages/PageFactory';

/**
 * Dashboard Overview — happy path & negative tests
 *
 * User story: "As a user I can view a personalised financial overview with KPI
 * cards, charts, and budget alerts so that I can understand my financial health
 * at a glance."
 *
 * Generated by the Amikoo Jira-to-tests worker (2026-09-09).
 */

test.describe('Dashboard Overview — happy path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    // Default landing is the Dashboard (Charts) section
    await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
  });

  test('all four KPI stat cards are visible on the dashboard', async ({ page }) => {
    await expect(page.getByText('Total Spent')).toBeVisible();
    await expect(page.getByText('Monthly Income')).toBeVisible();
    await expect(page.getByText('Net Savings')).toBeVisible();
    await expect(page.getByText('Transactions')).toBeVisible();
  });

  test('Monthly Income KPI always shows $6,500.00', async ({ page }) => {
    // Income is a fixed constant (MONTHLY_INCOME = 6500)
    const incomeCard = page.getByText('Monthly Income').locator('..');
    await expect(incomeCard).toContainText('$6,500.00');
  });

  test('month selector renders Jan, Feb, and Mar buttons', async ({ page }) => {
    // Only 3 months of seeded data exist
    const monthGroup = page.locator('div').filter({ hasText: /^JanFebMar$/ }).first();
    await expect(page.getByRole('button', { name: 'Jan' }).first()).toBeVisible();
    await expect(page.getByRole('button', { name: 'Feb' }).first()).toBeVisible();
    await expect(page.getByRole('button', { name: 'Mar' }).first()).toBeVisible();
  });

  test('switching to January updates the Total Spent KPI', async ({ page }) => {
    // Read March total first (default)
    const marchText = await page
      .getByText('Total Spent')
      .locator('..')
      .getByText(/\$[\d,]+/)
      .first()
      .textContent();

    // Switch to January
    await page.getByRole('button', { name: 'Jan' }).first().click();

    const janText = await page
      .getByText('Total Spent')
      .locator('..')
      .getByText(/\$[\d,]+/)
      .first()
      .textContent();

    // Both must contain a dollar amount, and they can (legitimately) differ
    expect(marchText).toMatch(/\$[\d,]+/);
    expect(janText).toMatch(/\$[\d,]+/);
  });

  test('Recent Transactions card shows at least one transaction row', async ({ page }) => {
    await expect(page.getByText('Recent Transactions')).toBeVisible();

    // Each row has a date string like "2026-01-xx"
    const txnRow = page.locator('div').filter({ hasText: /2026-\d{2}-\d{2}/ }).first();
    await expect(txnRow).toBeVisible();
  });

  test('Spending by Category chart section is rendered', async ({ page }) => {
    await expect(page.getByText('Spending by Category')).toBeVisible();
    // Recharts SVG element indicates the chart mounted
    await expect(page.locator('.recharts-wrapper').first()).toBeVisible();
  });

  test('Cumulative Spending chart is visible', async ({ page }) => {
    await expect(page.getByText('Cumulative Spending')).toBeVisible();
  });

  test('Monthly Comparison chart is visible', async ({ page }) => {
    await expect(page.getByText('Monthly Comparison')).toBeVisible();
  });

  test('Net Savings KPI is positive (income exceeds spending in demo data)', async ({ page }) => {
    const savingsCard = page.getByText('Net Savings').locator('..');
    const savingsText = await savingsCard.getByText(/\$[\d,]+/).first().textContent();
    // The demo user earns $6,500 and spends less — savings must be > $0
    const value = parseFloat((savingsText ?? '0').replace(/[$,]/g, ''));
    expect(value).toBeGreaterThan(0);
  });
});

test.describe('Dashboard Overview — negative path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
  });

  test('dashboard is NOT accessible without logging in', async ({ page }) => {
    // Log out to start fresh
    await page.getByRole('button', { name: /sign out/i }).click();

    // The Overview heading must NOT be visible on the login screen
    await expect(page.getByRole('heading', { name: 'Overview' })).not.toBeVisible();

    // The Sign In button must be visible instead
    await expect(new PageFactory(page).login().signInButton).toBeVisible();
  });

  test('navigating away from Charts and back restores all KPI cards', async ({ page }) => {
    // Leave the dashboard
    await page.getByRole('button', { name: /expenses/i }).click();
    await expect(page.getByRole('heading', { name: 'Expenses' })).toBeVisible();

    // Return to Charts
    await page.getByRole('button', { name: 'Charts' }).click();

    // All 4 KPIs should still be present
    await expect(page.getByText('Total Spent')).toBeVisible();
    await expect(page.getByText('Monthly Income')).toBeVisible();
    await expect(page.getByText('Net Savings')).toBeVisible();
    await expect(page.getByText('Transactions')).toBeVisible();
  });

  test('Budget Alerts section only appears when at least one category exceeds 50% of budget', async ({ page }) => {
    // With the seeded data the Budget Alerts card may or may not appear;
    // when it does, it must be above the "Recent Transactions" section.
    const alertsHeading = page.getByText('Budget Alerts');
    const recentHeading = page.getByText('Recent Transactions');

    // At minimum, Recent Transactions must always be visible
    await expect(recentHeading).toBeVisible();

    const alertsVisible = await alertsHeading.isVisible();
    if (alertsVisible) {
      // Alerts card should list at least one category row
      await expect(page.locator('div').filter({ hasText: /% / }).first()).toBeVisible();
    }
  });

  test('Total Spent is never negative in demo data', async ({ page }) => {
    for (const monthName of ['Jan', 'Feb', 'Mar']) {
      await page.getByRole('button', { name: monthName }).first().click();
      const spentText = await page
        .getByText('Total Spent')
        .locator('..')
        .getByText(/\$[\d,]+/)
        .first()
        .textContent();
      const value = parseFloat((spentText ?? '0').replace(/[$,]/g, ''));
      expect(value).toBeGreaterThanOrEqual(0);
    }
  });
});
