import { test, expect } from '@playwright/test';
import { PageFactory } from './pages/PageFactory';

/**
 * Expenses module — happy path and negative tests.
 *
 * User story: As a logged-in user I want to record, search, filter, and
 * sort my expenses so that I can track where my money goes and find
 * specific transactions quickly.
 *
 * Acceptance criteria:
 *   ✅ Adding a new expense via the form inserts it into the transaction table.
 *   ✅ Searching by description filters the visible rows to matching ones.
 *   ✅ Filtering by category shows only transactions of that category.
 *   ✅ Sorting by Amount (desc) puts the highest amount first.
 *   ✅ Sorting by Amount (asc) reverses the order.
 *   ❌ Searching for a term that matches no transaction shows the empty state.
 *   ❌ Saving the form without a description or amount does not add a row.
 */

test.describe('Expenses — Add Expense (happy path)', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.expenses().navigate();
  });

  test('clicking "Add Expense" reveals the add-expense form', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.openAddForm();

    await expect(expenses.descriptionInput).toBeVisible();
    await expect(expenses.amountInput).toBeVisible();
    await expect(expenses.saveButton).toBeVisible();
  });

  test('adding a new expense inserts a new row into the transaction table', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    const initialCount = await expenses.tableRows.count();

    await expenses.openAddForm();
    await expenses.addExpense('Test Coffee Shop', '12.50', 'Food');

    // The form should close and the row count should increase by exactly 1
    await expect(expenses.tableRows).toHaveCount(initialCount + 1);
  });

  test('the newly added expense description appears in the transaction table', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.openAddForm();
    await expenses.addExpense('Unique Bookstore Visit', '27.00', 'Entertainment');

    await expect(page.getByText('Unique Bookstore Visit')).toBeVisible();
  });

  test('the newly added expense amount appears in the table with a red negative format', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.openAddForm();
    await expenses.addExpense('Gym Top-up', '55.00', 'Health');

    // Amounts render as "-$55.00" in the rightmost column with text-red-400
    await expect(page.getByText('-$55.00')).toBeVisible();
  });

  test('the footer count increases by 1 after adding an expense', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Parse the initial count from "N transactions"
    const footerText = await expenses.footerCount.textContent() ?? '';
    const initialCount = parseInt(footerText.match(/\d+/)?.[0] ?? '0', 10);

    await expenses.openAddForm();
    await expenses.addExpense('New Transport', '8.00', 'Transport');

    const updatedText = await expenses.footerCount.textContent() ?? '';
    const updatedCount = parseInt(updatedText.match(/\d+/)?.[0] ?? '0', 10);

    expect(updatedCount).toBe(initialCount + 1);
  });
});

test.describe('Expenses — Search & Filter (happy path)', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.expenses().navigate();
  });

  test('searching by description filters the transaction table to matching rows', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // "Rent" is a description generated by the Housing seed data
    await expenses.search('Rent');

    // Every visible row must contain "Rent" in its description cell
    const rows = expenses.tableRows;
    const count = await rows.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < count; i++) {
      const rowText = await rows.nth(i).textContent();
      expect(rowText?.toLowerCase()).toContain('rent');
    }
  });

  test('filtering by Housing category shows only Housing transactions', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.filterByCategory('Housing');

    const rows = expenses.tableRows;
    const count = await rows.count();
    expect(count).toBeGreaterThan(0);

    // Each row should have the Housing category badge text
    for (let i = 0; i < count; i++) {
      await expect(rows.nth(i)).toContainText('Housing');
    }
  });

  test('clearing the category filter back to All restores all transactions', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    const allCount = await expenses.tableRows.count();

    // Narrow to one category first
    await expenses.filterByCategory('Food');
    const foodCount = await expenses.tableRows.count();
    expect(foodCount).toBeLessThan(allCount);

    // Reset to All
    await expenses.filterByCategory('All');
    await expect(expenses.tableRows).toHaveCount(allCount);
  });

  test('sorting by Amount (desc) places the highest-value row first', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Click once to sort desc
    await expenses.amountSortHeader.click();

    const firstAmount = await expenses.firstRowAmount();
    const rows = expenses.tableRows;
    const count = await rows.count();

    // Parse first and last amounts (format: "-$1,234.56")
    const parse = (s: string) => parseFloat(s.replace(/[^0-9.]/g, ''));
    const lastAmount = await rows.last().locator('td').last().textContent() ?? '';

    expect(parse(firstAmount)).toBeGreaterThanOrEqual(parse(lastAmount));
  });

  test('sorting by Amount (asc) places the lowest-value row first', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Click twice: first click = desc, second click = asc
    await expenses.amountSortHeader.click();
    await expenses.amountSortHeader.click();

    const firstAmount = await expenses.firstRowAmount();
    const rows = expenses.tableRows;
    const lastAmount = await rows.last().locator('td').last().textContent() ?? '';

    const parse = (s: string) => parseFloat(s.replace(/[^0-9.]/g, ''));
    expect(parse(firstAmount)).toBeLessThanOrEqual(parse(lastAmount));
  });
});

test.describe('Expenses — Search & Filter (negative path)', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.expenses().navigate();
  });

  test('searching for a term that matches no transactions shows the empty-state row', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.search('xxxxxxnonexistentterm');

    await expect(expenses.emptyState).toBeVisible();
    await expect(expenses.tableRows).toHaveCount(0);
  });

  test('footer shows "0 transactions" when search returns no results', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.search('xxxxxxnonexistentterm');

    await expect(expenses.footerCount).toContainText('0 transaction');
  });

  test('submitting the add-expense form without a description does not add a new row', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    const initialCount = await expenses.tableRows.count();

    await expenses.openAddForm();
    // Leave description blank — only fill the amount
    await expenses.amountInput.fill('50.00');
    await expenses.saveButton.click();

    // Row count should remain unchanged (app guards against empty description)
    await expect(expenses.tableRows).toHaveCount(initialCount);
  });

  test('submitting the add-expense form without an amount does not add a new row', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    const initialCount = await expenses.tableRows.count();

    await expenses.openAddForm();
    // Fill description but leave amount blank
    await expenses.descriptionInput.fill('No Amount Expense');
    await expenses.saveButton.click();

    // Row count should remain unchanged (app guards against empty amount)
    await expect(expenses.tableRows).toHaveCount(initialCount);
  });

  test('selecting a category filter then typing a non-matching search shows empty state', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Narrow to Food first
    await expenses.filterByCategory('Food');
    // Then search for something that will never appear in Food descriptions
    await expenses.search('zzznomatch');

    await expect(expenses.emptyState).toBeVisible();
  });
});
