import { test, expect } from '@playwright/test';
import { PageFactory } from './pages/PageFactory';

/**
 * Expense Management — happy path & negative tests
 *
 * User story: "As a user I can view, search, filter, and add expenses so that
 * I can track my spending across categories and months."
 *
 * Generated by the Amikoo Jira-to-tests worker (2026-09-09).
 */

test.describe('Expense Management — happy path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.expenses().navigate();
  });

  test('Expenses section loads with a heading and transaction rows', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Heading must be visible
    await expect(expenses.heading).toBeVisible();

    // At least one seeded transaction should appear in the table
    await expect(expenses.transactionRows.first()).toBeVisible();
  });

  test('Add Expense button opens the new expense form', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.openAddForm();

    // Form fields appear after toggling the panel
    await expect(expenses.formDescriptionInput).toBeVisible();
    await expect(expenses.formAmountInput).toBeVisible();
    await expect(expenses.formSaveButton).toBeVisible();
  });

  test('a new expense is added to the transaction table after saving', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Count rows before adding
    const countBefore = await expenses.transactionRows.count();

    await expenses.openAddForm();
    await expenses.addExpense('Coffee at Blue Bottle', '7.50');

    // The new row should appear at the top of the table
    await expect(expenses.transactionRows.first()).toContainText('Coffee at Blue Bottle');

    // Total row count must have increased by 1
    const countAfter = await expenses.transactionRows.count();
    expect(countAfter).toBe(countBefore + 1);
  });

  test('search filters the transaction table by description', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // First add a uniquely named transaction so the search is deterministic
    await expenses.openAddForm();
    await expenses.addExpense('UniqueCoffeeXYZ99', '5.00');

    // Search for it
    await expenses.search('UniqueCoffeeXYZ99');

    // Only the matching row(s) should remain visible
    await expect(expenses.transactionRows).toHaveCount(1);
    await expect(expenses.transactionRows.first()).toContainText('UniqueCoffeeXYZ99');
  });

  test('category filter shows only transactions of the selected category', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Filter by Housing — which always has exactly 1 seeded transaction per month
    await expenses.filterByCategory('Housing');

    const rows = expenses.transactionRows;
    const count = await rows.count();
    expect(count).toBeGreaterThanOrEqual(1);

    // Every visible row should bear the Housing category badge
    for (let i = 0; i < count; i++) {
      await expect(rows.nth(i)).toContainText('Housing');
    }
  });

  test('switching months updates the transaction list', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Note how many rows are shown for the current month (March, default)
    const marchCount = await expenses.transactionRows.count();

    // Switch to January
    await page.getByRole('button', { name: 'Jan' }).click();
    const janCount = await expenses.transactionRows.count();

    // Both months have seeded data; counts may differ but must be positive
    expect(marchCount).toBeGreaterThan(0);
    expect(janCount).toBeGreaterThan(0);
  });

  test('footer shows the correct transaction count and total', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    const rowCount = await expenses.transactionRows.count();

    // The footer label should report the same number
    await expect(page.locator('div').filter({ hasText: new RegExp(`^${rowCount} transactions?$`) }).first()).toBeVisible();

    // Total must contain a dollar sign
    await expect(page.locator('div').filter({ hasText: /Total:/ }).first()).toContainText('$');
  });
});

test.describe('Expense Management — negative path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.expenses().navigate();
  });

  test('saving an expense with no description and no amount does not add a new row', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    const countBefore = await expenses.transactionRows.count();

    await expenses.openAddForm();
    // Click Save without filling any fields
    await expenses.formSaveButton.click();

    // Row count must not change (the app guards against empty desc+amount)
    const countAfter = await expenses.transactionRows.count();
    expect(countAfter).toBe(countBefore);
  });

  test('searching for a non-existent term shows the empty state', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    await expenses.search('zzz_no_match_xyz');

    await expect(expenses.emptyStateCell).toBeVisible();
    await expect(expenses.transactionRows).toHaveCount(0);
  });

  test('filtering by a category with no transactions in the month shows empty state', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Switch to January then search for a term that matches nothing in that category
    await page.getByRole('button', { name: 'Jan' }).click();
    await expenses.filterByCategory('Health');
    await expenses.search('zzz_impossible_term_xyz');

    await expect(expenses.emptyStateCell).toBeVisible();
  });

  test('search is case-insensitive: lowercase query matches mixed-case description', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    // Add a transaction with a mixed-case description
    await expenses.openAddForm();
    await expenses.addExpense('MixedCaseSushi', '30.00');

    // Search using all-lowercase
    await expenses.search('mixedcasesushi');

    await expect(expenses.transactionRows).toHaveCount(1);
    await expect(expenses.transactionRows.first()).toContainText('MixedCaseSushi');
  });

  test('clearing the search field restores the full transaction list', async ({ page }) => {
    const expenses = new PageFactory(page).expenses();

    const totalRows = await expenses.transactionRows.count();

    // Apply a search that narrows results
    await expenses.search('Rent');
    const filteredCount = await expenses.transactionRows.count();
    expect(filteredCount).toBeLessThanOrEqual(totalRows);

    // Clear the search — all rows must return
    await expenses.search('');
    await expect(expenses.transactionRows).toHaveCount(totalRows);
  });
});
