import { test, expect } from '@playwright/test';
import { PageFactory } from './pages/PageFactory';

/**
 * Critical tests generated by Amikoo QA for PR #56:
 * "Rename Investments section to MoneyMaker"
 *
 * Two source changes drive all tests here:
 *   1. src/App.jsx ~L257 — sidebar item label: "Investments" → "MoneyMaker"
 *   2. src/App.jsx ~L711 — InvestmentsTab <h2>:  "Investments" → "MoneyMaker"
 *   3. tests/pages/InvestmentsPage.ts — navigate() updated to /moneymaker/i
 *
 * Happy-path (HP): confirm the primary success flows work under the new label.
 * Negative (NEG):  confirm the old label is gone and edge cases are handled.
 */

// ---------------------------------------------------------------------------
// Shared setup — log in and land on the app dashboard before each test
// ---------------------------------------------------------------------------
test.beforeEach(async ({ page }) => {
  const factory = new PageFactory(page);
  await factory.login().goto();
  await factory.login().loginAsDemo();
  // Guard: we are inside the app before any navigation
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
});

// ===========================================================================
// HAPPY-PATH TESTS
// ===========================================================================

test.describe('MoneyMaker rename — happy-path', () => {

  /**
   * HP-1: End-to-end POM validation.
   * InvestmentsPage.navigate() must use the renamed /moneymaker/i selector.
   * After calling it, both the sidebar button and the section <h2> must show
   * "MoneyMaker" — confirming the page object and both source changes are correct.
   */
  test(
    'HP-1: InvestmentsPage.navigate() opens MoneyMaker and both sidebar button and heading read "MoneyMaker"',
    async ({ page }) => {
      const factory = new PageFactory(page);
      await factory.investments().navigate();

      // Sidebar button must show the renamed label
      await expect(page.getByRole('button', { name: 'MoneyMaker' })).toBeVisible();

      // Section heading (the h2 changed in App.jsx ~L711) must match
      await expect(page.getByRole('heading', { name: 'MoneyMaker' })).toBeVisible();
    }
  );

  /**
   * HP-2: All four sub-tabs remain functional under the renamed section.
   * The rename must not break the sub-tab navigation inside MoneyMaker.
   */
  test(
    'HP-2: all four sub-tabs (Fund Cards, Compare, Calculator, Portfolio Builder) are reachable within MoneyMaker',
    async ({ page }) => {
      const factory = new PageFactory(page);
      const investments = factory.investments();

      await investments.navigate();

      // Fund Cards — default sub-tab, should already have at least one card
      await expect(investments.fundCards.first()).toBeVisible();

      // Compare sub-tab — the button must be visible and clickable
      await investments.goToSubTab('Compare');
      await expect(page.getByRole('button', { name: 'Compare' })).toBeVisible();

      // Calculator sub-tab — the investment amount input must appear
      await investments.goToSubTab('Calculator');
      await expect(investments.calculatorAmountInput).toBeVisible();

      // Portfolio Builder sub-tab — at least one slider must be present
      await investments.goToSubTab('Portfolio Builder');
      const sliderCount = await investments.portfolioSliders.count();
      expect(sliderCount).toBeGreaterThan(0);

      // Heading must remain "MoneyMaker" throughout all sub-tab switches
      await expect(page.getByRole('heading', { name: 'MoneyMaker' })).toBeVisible();
    }
  );

  /**
   * HP-3: Fund selection (up to 3 funds) still works under the MoneyMaker name.
   * This is the core user flow of the section — a rename must not break it.
   */
  test(
    'HP-3: selecting up to 3 funds in MoneyMaker works correctly and selected badges are shown',
    async ({ page }) => {
      const factory = new PageFactory(page);
      const investments = factory.investments();

      await investments.navigate();

      // Ensure there are enough cards to select
      const cardCount = await investments.fundCards.count();
      expect(cardCount).toBeGreaterThanOrEqual(3);

      // Select the first three fund cards
      await investments.selectFundCard(0);
      await investments.selectFundCard(1);
      await investments.selectFundCard(2);

      // Exactly 3 "✓ Selected" badges must appear
      await expect(investments.selectedBadges).toHaveCount(3);

      // Heading must still read "MoneyMaker" throughout the interaction
      await expect(page.getByRole('heading', { name: 'MoneyMaker' })).toBeVisible();
    }
  );
});

// ===========================================================================
// NEGATIVE / EDGE-CASE TESTS
// ===========================================================================

test.describe('MoneyMaker rename — negative / edge-case', () => {

  /**
   * NEG-1: The old "Investments" sidebar button must not exist anywhere in the DOM.
   * An accidental revert or partial rename would be caught here immediately.
   * (Exact-match check prevents false positives from unrelated text.)
   */
  test(
    'NEG-1: no sidebar button with the label "Investments" exists after the rename',
    async ({ page }) => {
      // Exact match — "Investments" must be completely gone from role=button elements
      await expect(
        page.getByRole('button', { name: 'Investments', exact: true })
      ).toHaveCount(0);

      // Broader regex — also catches partial labels like "My Investments"
      await expect(
        page.getByRole('button', { name: /^investments$/i })
      ).toHaveCount(0);
    }
  );

  /**
   * NEG-2: No heading with the old label "Investments" should appear after navigating
   * into the section, verifying the h2 change in App.jsx ~L711 is in effect.
   */
  test(
    'NEG-2: no page heading reads "Investments" after navigating into MoneyMaker',
    async ({ page }) => {
      const factory = new PageFactory(page);
      await factory.investments().navigate();

      // The section <h2> must not show the stale "Investments" text
      await expect(
        page.getByRole('heading', { name: /^investments$/i })
      ).toHaveCount(0);

      // And the correct heading must be present (sanity assertion)
      await expect(
        page.getByRole('heading', { name: 'MoneyMaker' })
      ).toBeVisible();
    }
  );

  /**
   * NEG-3: Selecting a 4th fund must still be rejected by the 3-fund limit —
   * confirming the rename did not accidentally remove the selection-limit guard.
   */
  test(
    'NEG-3: selecting a 4th fund in MoneyMaker is still blocked by the 3-fund selection limit',
    async ({ page }) => {
      const factory = new PageFactory(page);
      const investments = factory.investments();

      await investments.navigate();

      // Require at least 4 cards to be able to attempt a 4th selection
      const cardCount = await investments.fundCards.count();
      expect(cardCount).toBeGreaterThanOrEqual(4);

      // Select the maximum of 3 cards
      await investments.selectFundCard(0);
      await investments.selectFundCard(1);
      await investments.selectFundCard(2);

      // Attempt to add a 4th
      await investments.selectFundCard(3);

      // Selection count must remain at 3 — the 4th card must be ignored
      await expect(investments.selectedBadges).toHaveCount(3);

      // The 4th card must not show the ring-selection highlight
      await expect(investments.fundCards.nth(3)).not.toHaveClass(/ring-1/);
    }
  );
});
