import { test, expect } from '@playwright/test';
import { PageFactory } from './pages/PageFactory';

/**
 * Settings / Profile — happy path & negative tests
 *
 * User story: "As a user I can update my profile (name, email, currency)
 * and toggle preferences so that the app reflects my identity and choices."
 *
 * Generated by the Amikoo Jira-to-tests worker (2026-09-09).
 */

test.describe('Settings Profile — happy path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.settings().navigate();
  });

  test('Settings page loads with Profile Information and Preferences sections', async ({ page }) => {
    await expect(page.getByText('Profile Information')).toBeVisible();
    await expect(page.getByText('Preferences')).toBeVisible();
  });

  test('Profile form pre-fills with the demo user defaults', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    // The seeded user is "Alex Morgan" / "alex@wealthpulse.demo"
    await expect(settings.nameInput).toHaveValue('Alex Morgan');
    await expect(settings.emailInput).toHaveValue('alex@wealthpulse.demo');
    await expect(settings.currencySelect).toHaveValue('USD');
  });

  test('saving a new name shows the ✓ Saved! confirmation', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    await settings.updateProfile('Jordan Rivera', 'jordan@wealthpulse.demo');

    // After clicking Save the button text changes to "✓ Saved!" briefly
    await expect(settings.savedConfirmation).toBeVisible();
  });

  test('saved name persists in the profile card immediately after saving', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    await settings.updateProfile('Jordan Rivera', 'jordan@wealthpulse.demo');
    await expect(settings.savedConfirmation).toBeVisible();

    // The avatar initials section and the preview card inside Settings update
    await expect(page.getByText('Jordan Rivera').first()).toBeVisible();
  });

  test('currency can be changed to EUR and saved', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    await settings.updateProfile('Alex Morgan', 'alex@wealthpulse.demo', 'EUR');

    await expect(settings.savedConfirmation).toBeVisible();

    // After saving, the select should reflect the chosen currency
    await expect(settings.currencySelect).toHaveValue('EUR');
  });

  test('currency can be changed to GBP and saved', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    await settings.updateProfile('Alex Morgan', 'alex@wealthpulse.demo', 'GBP');
    await expect(settings.savedConfirmation).toBeVisible();
    await expect(settings.currencySelect).toHaveValue('GBP');
  });

  test('Preferences section lists Dark Mode, Email Notifications, and Monthly Reports', async ({ page }) => {
    await expect(page.getByText('Dark Mode')).toBeVisible();
    await expect(page.getByText('Email Notifications')).toBeVisible();
    await expect(page.getByText('Monthly Reports')).toBeVisible();
  });

  test('Settings section is accessible via the sidebar navigation button', async ({ page }) => {
    // Navigate away then come back via sidebar
    await page.getByRole('button', { name: /expenses/i }).click();
    await expect(page.getByRole('heading', { name: 'Expenses' })).toBeVisible();

    await page.getByRole('button', { name: /settings/i }).click();
    await expect(new PageFactory(page).settings().heading).toBeVisible();
  });
});

test.describe('Settings Profile — negative path', () => {
  test.beforeEach(async ({ page }) => {
    const factory = new PageFactory(page);
    await factory.login().goto();
    await factory.login().loginAsDemo();
    await factory.settings().navigate();
  });

  test('saving with an empty name field shows an empty name in the profile card', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    // Clear the name and save — the app does not block this,
    // but the avatar initials strip should gracefully handle an empty string
    await settings.nameInput.fill('');
    await settings.saveButton.click();

    // Confirmation should still appear (the app does not validate)
    await expect(settings.savedConfirmation).toBeVisible();
  });

  test('saving with an invalid email format does not prevent saving (no client-side validation)', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    // The app does not currently enforce email format — this confirms the behaviour
    await settings.updateProfile('Alex Morgan', 'not-an-email');
    await expect(settings.savedConfirmation).toBeVisible();
  });

  test('confirmation banner disappears after ~2 seconds', async ({ page }) => {
    const settings = new PageFactory(page).settings();

    await settings.updateProfile('Alex Morgan', 'alex@wealthpulse.demo');
    await expect(settings.savedConfirmation).toBeVisible();

    // Wait for the app's 2-second timeout to elapse, then the button should revert
    await expect(settings.savedConfirmation).not.toBeVisible({ timeout: 4000 });
    await expect(settings.saveButton).toBeVisible();
  });

  test('settings changes do not persist after logging out and logging back in', async ({ page }) => {
    const factory = new PageFactory(page);
    const settings = factory.settings();

    // Update the name
    await settings.updateProfile('Temporary Name', 'temp@wealthpulse.demo');
    await expect(settings.savedConfirmation).toBeVisible();

    // Log out
    await page.getByRole('button', { name: /sign out/i }).click();
    await expect(factory.login().signInButton).toBeVisible();

    // Log back in
    await factory.login().loginAsDemo();
    await factory.settings().navigate();

    // The app stores state in memory; a fresh session resets to the seeded defaults
    await expect(settings.nameInput).toHaveValue('Alex Morgan');
  });

  test('Settings is not reachable without authentication', async ({ page }) => {
    const factory = new PageFactory(page);

    // Sign out first
    await page.getByRole('button', { name: /sign out/i }).click();
    await expect(factory.login().signInButton).toBeVisible();

    // Settings heading must NOT be visible
    await expect(factory.settings().heading).not.toBeVisible();
  });
});
